# Generated by Django 4.0 on 2022-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagefusion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='使用次数'),
        ),
    ]
