# Generated by Django 4.0 on 2022-04-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagefusion', '0002_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count',
        ),
    ]
