# site scope vars
timezone: Asia/Shanghai

title: 医学影像处理网站
title_en: Medical Image Processing
email: someone@some.com
baseurl: ""

# 构建时排除的文件
exclude:
  - Gemfile*
  - README.md
  - auto_sync.sh
  - install_jekyll.sh
  - .*
  - install_service.sh
  - isc_site_auto_ci.service
  - TIMESTAMP.txt

plugins:
  - jekyll-redirect-from
